### ISSUE TITLE
The base.apk file doesn't appear in the Youtube Vanced zip file. 🤨

### ISSUE THREAD

**Issue by Dhyfer1** [Norikiru/VancedInstall#1]
Hi @Norikiru 

I downloaded the zip file for the latest stable version of Youtube Vanced (17.03.38) and followed the instructions for installation through SAI, but I got stuck at step 5, specifically the next step:

>We would need to pick 4 apk files:
>- `base.apk` (**DON'T USE `stock.apk`** or else it would install the stock app instead of Vanced.)

Well, where is the base.apk file?. The base.apk file doesn't exist in any of the subfolders inside the nonroot and root folders, but the other apk files mentioned (stock.apk, dpi.apk etc) do appear. How is it possible that you forgot this important file?

So please, place the base.apk file in the required folder(s), that's all.

**Comment by carince** [comment]
Sorry for the confusion, @Dhyfer1 

I have made tutorials on how to install Vanced on rooted and non-rooted phones up on YouTube:
Non-root: https://youtu.be/xtFnimiTvwQ
Root: https://youtu.be/92EDq8x5UxE

I thought I had updated the readme file directing it to the YouTube videos, I guess that I forgot about it and had focused on other IRL matters. Ill be updating the readme file soon that would redirect people to the YouTube videos for the installation, and update the steps soon.

**Comment by Dhyfer1** [comment]
Hi again.

Thank you very much for the videos, it has helped me a lot the procedure to install the root version, it's more understandable with the video. And I also like your repository, it's the most complete I could find with all the files used by Vanced, that's why I have it starred. 

Thanks for the video description, I look forward to the Readme file update soon. 

Good day.
