### ISSUE TITLE
Root version removes itself after a reboot

### ISSUE THREAD

**Issue by lifehackerhansol** [Norikiru/VancedInstall#2]
I'm aware that there may not be much hope in solving this issue given development is gone forever, but I'll post it anyhow:

The root version, after following the guide properly, appears to simply uninstall itself after a reboot. I haven't found such a problem with the non-root version thankfully, so I'm using that in the meantime. Not entirely sure what is going on.

I wanted to ask if anyone else was facing the same issue: if so, maybe we could update the README about it and try to suggest the nonroot version.

**Comment by carince** [comment]
For me the root version of Vanced doesnt uninstall itself after a reboot, only thing that uninstalls Vanced for me is Google Play Store updating YouTube out of nowhere even if I set the setting to not auto-update. Ill dig through Vanced Manager and find if it has a fix for it, afaik theres a setting to fix that exact problem.

**Comment by reggiiie** [comment]
same here

**Comment by reggiiie** [comment]
Do not replace the base.apk, what you should do instead (and this is what Vanced Manager did when installing Vanced) is:

- Go to /data/adb/service.d and create a file called vanced.sh and put this inside

```
#!/system/bin/sh
while [ "$(getprop sys.boot_completed | tr -d '\r')" != "1" ]; do sleep 1; done
sleep 1
chcon u:object_r:apk_data_file:s0 /data/adb/Vanced/base.apk
mount -o bind /data/adb/Vanced/base.apk /data/app/SOME_FOLDER/SOME_FOLDER/base.apk
```
- replace the paths to both base.apk-s with their actual path, I moved the Themes/dark.apk to /data/adb/Vanced/base.apk
- give the script executable permissions
- reboot
- if nothing happens you can try running the mount command in termux with root privileges to see if it throws any error

**Comment by carince** [comment]
> Do not replace the base.apk, what you should do instead (and this is what Vanced Manager did when installing Vanced) is:
> 
> * Go to /data/adb/service.d and create a file called vanced.sh and put this inside
> 
> ```
> #!/system/bin/sh
> while [ "$(getprop sys.boot_completed | tr -d '\r')" != "1" ]; do sleep 1; done
> sleep 1
> chcon u:object_r:apk_data_file:s0 /data/adb/Vanced/base.apk
> mount -o bind /data/adb/Vanced/base.apk /data/app/SOME_FOLDER/SOME_FOLDER/base.apk
> ```
> 
> * replace the paths to both base.apk-s with their actual path, I moved the Themes/dark.apk to /data/adb/Vanced/base.apk
> * give the script executable permissions
> * reboot
> * if nothing happens you can try running the mount command in termux with root privileges to see if it throws any error

thanks for getting the actual script from the Vanced Manager lol (def didnt played games for the past 2 weeks), anyways, ill make a updated tutorial with voiceover to make my life easier and probably for you guys to.
